services:

  users:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-app:latest
    container_name: users
    env_file:
      - .env
    command: uv run users
    ports:
      - "8081:8081"
    restart: unless-stopped

  analyzer:
    image: demo-app:latest
    container_name: analyzer
    env_file:
      - .env
    command: uv run analyzer
    ports:
      - "8083:8083"
    depends_on:
      - users
    restart: unless-stopped

  ui:
    image: demo-app:latest
    container_name: ui
    env_file:
      - .env
    command: uv run ui
    ports:
      - "8501:8501"
    depends_on:
      - users
      - analyzer
    restart: unless-stopped
