services:
  analyzer:
    image: ghcr.io/astral-sh/uv:python3.10-bookworm
    container_name: analyzer
    working_dir: /app
    environment:
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uv run analyzer
    ports:
      - "8083:5000"
    restart: unless-stopped
